// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/B022MC/b022hub/ent/paymentorder"
	"github.com/B022MC/b022hub/ent/predicate"
	"github.com/B022MC/b022hub/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdate) SetProvider(v string) *PaymentOrderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProvider(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *PaymentOrderUpdate) SetOutTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOutTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (_u *PaymentOrderUpdate) SetProviderTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderTradeNo(v)
	return _u
}

// SetNillableProviderTradeNo sets the "provider_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderTradeNo(*v)
	}
	return _u
}

// ClearProviderTradeNo clears the value of the "provider_trade_no" field.
func (_u *PaymentOrderUpdate) ClearProviderTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearProviderTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PaymentOrderUpdate) SetTitle(v string) *PaymentOrderUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableTitle(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdate) SetAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdate) AddAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *PaymentOrderUpdate) SetCreditedAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetCreditedAmount()
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCreditedAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// AddCreditedAmount adds value to the "credited_amount" field.
func (_u *PaymentOrderUpdate) AddCreditedAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddCreditedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRawProviderPayload sets the "raw_provider_payload" field.
func (_u *PaymentOrderUpdate) SetRawProviderPayload(v string) *PaymentOrderUpdate {
	_u.mutation.SetRawProviderPayload(v)
	return _u
}

// SetNillableRawProviderPayload sets the "raw_provider_payload" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRawProviderPayload(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRawProviderPayload(*v)
	}
	return _u
}

// ClearRawProviderPayload clears the value of the "raw_provider_payload" field.
func (_u *PaymentOrderUpdate) ClearRawProviderPayload() *PaymentOrderUpdate {
	_u.mutation.ClearRawProviderPayload()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := paymentorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderTradeNo(); ok {
		if err := paymentorder.ProviderTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := paymentorder.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(paymentorder.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderTradeNo(); ok {
		_spec.SetField(paymentorder.FieldProviderTradeNo, field.TypeString, value)
	}
	if _u.mutation.ProviderTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(paymentorder.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawProviderPayload(); ok {
		_spec.SetField(paymentorder.FieldRawProviderPayload, field.TypeString, value)
	}
	if _u.mutation.RawProviderPayloadCleared() {
		_spec.ClearField(paymentorder.FieldRawProviderPayload, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdateOne) SetProvider(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProvider(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *PaymentOrderUpdateOne) SetOutTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOutTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (_u *PaymentOrderUpdateOne) SetProviderTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderTradeNo(v)
	return _u
}

// SetNillableProviderTradeNo sets the "provider_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderTradeNo(*v)
	}
	return _u
}

// ClearProviderTradeNo clears the value of the "provider_trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearProviderTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderTradeNo()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PaymentOrderUpdateOne) SetTitle(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableTitle(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdateOne) SetAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdateOne) AddAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *PaymentOrderUpdateOne) SetCreditedAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetCreditedAmount()
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCreditedAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// AddCreditedAmount adds value to the "credited_amount" field.
func (_u *PaymentOrderUpdateOne) AddCreditedAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddCreditedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRawProviderPayload sets the "raw_provider_payload" field.
func (_u *PaymentOrderUpdateOne) SetRawProviderPayload(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetRawProviderPayload(v)
	return _u
}

// SetNillableRawProviderPayload sets the "raw_provider_payload" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRawProviderPayload(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRawProviderPayload(*v)
	}
	return _u
}

// ClearRawProviderPayload clears the value of the "raw_provider_payload" field.
func (_u *PaymentOrderUpdateOne) ClearRawProviderPayload() *PaymentOrderUpdateOne {
	_u.mutation.ClearRawProviderPayload()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := paymentorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderTradeNo(); ok {
		if err := paymentorder.ProviderTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := paymentorder.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(paymentorder.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderTradeNo(); ok {
		_spec.SetField(paymentorder.FieldProviderTradeNo, field.TypeString, value)
	}
	if _u.mutation.ProviderTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(paymentorder.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawProviderPayload(); ok {
		_spec.SetField(paymentorder.FieldRawProviderPayload, field.TypeString, value)
	}
	if _u.mutation.RawProviderPayloadCleared() {
		_spec.ClearField(paymentorder.FieldRawProviderPayload, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
